/**
 * Error code constants
 * Must match API-ERROR-CODES.MD exactly
 */
export const ERROR_CODES = {
  // 400 Bad Request
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_ENUM: 'INVALID_ENUM',
  INVALID_PAGINATION: 'INVALID_PAGINATION',

  // 401 Unauthorized
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // 403 Forbidden
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  OWNER_ONLY: 'OWNER_ONLY',

  // 404 Not Found
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  DISH_NOT_FOUND: 'DISH_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  CART_NOT_FOUND: 'CART_NOT_FOUND',

  // 409 Conflict
  CONFLICT: 'CONFLICT',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_SLUG: 'DUPLICATE_SLUG',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',

  // 422 Unprocessable Entity
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  CART_EMPTY: 'CART_EMPTY',
  RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',
  DISH_UNAVAILABLE: 'DISH_UNAVAILABLE',

  // 429 Rate Limited
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // 500 Server Error
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

/**
 * HTTP status mapping for error codes
 */
export const ERROR_HTTP_STATUS: Record<string, number> = {
  INVALID_REQUEST: 400,
  MISSING_REQUIRED_FIELD: 400,
  INVALID_EMAIL: 400,
  INVALID_PHONE: 400,
  INVALID_UUID: 400,
  INVALID_ENUM: 400,
  INVALID_PAGINATION: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  SESSION_EXPIRED: 401,
  FORBIDDEN: 403,
  INSUFFICIENT_PERMISSIONS: 403,
  OWNER_ONLY: 403,
  NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  RESTAURANT_NOT_FOUND: 404,
  DISH_NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,
  CART_NOT_FOUND: 404,
  CONFLICT: 409,
  DUPLICATE_EMAIL: 409,
  DUPLICATE_SLUG: 409,
  INVALID_STATE_TRANSITION: 409,
  INSUFFICIENT_STOCK: 422,
  CART_EMPTY: 422,
  RESTAURANT_CLOSED: 422,
  DISH_UNAVAILABLE: 422,
  RATE_LIMIT_EXCEEDED: 429,
  INTERNAL_ERROR: 500,
  DATABASE_ERROR: 500,
};
